#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: CI

on:
  push:
    branches:
      - master
      - branch-*
  pull_request:
    branches:
      - master
      - branch-*

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java:
          - 8
          - 11
        spark:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        spark-archive: [""]
        exclude-tags: [""]
    env:
      SPARK_LOCAL_IP: localhost
    steps:
      - uses: actions/checkout@v2
      - name: Tune Runner VM
        uses: ./.github/actions/tune-runner-vm
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: 'maven'
          check-latest: false
      - name: Build and test with maven w/o linters
        run: >-
          ./build/mvn clean install
          -Dmaven.javadoc.skip=true
          -Drat.skip=true
          -Dscalastyle.skip=true
          -Dspotless.check.skip
          -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
          -Pspark-${{ matrix.spark }}
          ${{ matrix.spark-archive }}
          ${{ matrix.exclude-tags }}
      - name: Code coverage
        if: |
          matrix.java == 8 &&
          matrix.spark == '3.2' &&
          matrix.spark-archive == ''
        uses: codecov/codecov-action@v2
        with:
          verbose: true
      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-log
          path: |
            **/target/unit-tests.log
            **/kyuubi-flink-sql-engine.log*
            **/kyuubi-spark-sql-engine.log*
            **/kyuubi-trino-sql-engine.log*

